-- Rollback migration 001
DROP TABLE IF EXISTS browser_runs CASCADE;
DROP TABLE IF EXISTS execution_runs CASCADE;
DROP TABLE IF EXISTS claims CASCADE;
DROP TABLE IF EXISTS action_cards CASCADE;
DROP TABLE IF EXISTS workflow_steps CASCADE;
DROP TABLE IF EXISTS videos CASCADE;
DROP TABLE IF EXISTS workflow_jobs CASCADE;
DROP TABLE IF EXISTS users CASCADE;
